#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 141
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 1
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 8

enum ts_symbol_identifiers {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  anon_sym_LBRACE = 3,
  anon_sym_COLON = 4,
  anon_sym_POUND = 5,
  anon_sym_0 = 6,
  anon_sym_DOT = 7,
  anon_sym_STAR = 8,
  anon_sym_RBRACE = 9,
  aux_sym_fill_token1 = 10,
  anon_sym_LT = 11,
  anon_sym_CARET = 12,
  anon_sym_GT = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_QMARK = 16,
  anon_sym_x_QMARK = 17,
  anon_sym_X_QMARK = 18,
  anon_sym_o = 19,
  anon_sym_x = 20,
  anon_sym_X = 21,
  anon_sym_p = 22,
  anon_sym_b = 23,
  anon_sym_e = 24,
  anon_sym_E = 25,
  anon_sym_DOLLAR = 26,
  sym_text = 27,
  sym_integer = 28,
  sym_identifier = 29,
  sym_format_string = 30,
  sym_maybe_format = 31,
  sym_format = 32,
  sym_fill = 33,
  sym_align = 34,
  sym_sign = 35,
  sym_type = 36,
  sym_count = 37,
  sym_parameter = 38,
  sym_argument = 39,
  aux_sym_format_string_repeat1 = 40,
  alias_sym_width = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_POUND] = "#",
  [anon_sym_0] = "0",
  [anon_sym_DOT] = ".",
  [anon_sym_STAR] = "*",
  [anon_sym_RBRACE] = "}",
  [aux_sym_fill_token1] = "fill_token1",
  [anon_sym_LT] = "<",
  [anon_sym_CARET] = "^",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_QMARK] = "\?",
  [anon_sym_x_QMARK] = "x\?",
  [anon_sym_X_QMARK] = "X\?",
  [anon_sym_o] = "o",
  [anon_sym_x] = "x",
  [anon_sym_X] = "X",
  [anon_sym_p] = "p",
  [anon_sym_b] = "b",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym_DOLLAR] = "$",
  [sym_text] = "text",
  [sym_integer] = "integer",
  [sym_identifier] = "identifier",
  [sym_format_string] = "format_string",
  [sym_maybe_format] = "maybe_format",
  [sym_format] = "format",
  [sym_fill] = "fill",
  [sym_align] = "align",
  [sym_sign] = "sign",
  [sym_type] = "type",
  [sym_count] = "count",
  [sym_parameter] = "parameter",
  [sym_argument] = "argument",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
  [alias_sym_width] = "width",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_fill_token1] = aux_sym_fill_token1,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_x_QMARK] = anon_sym_x_QMARK,
  [anon_sym_X_QMARK] = anon_sym_X_QMARK,
  [anon_sym_o] = anon_sym_o,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_p] = anon_sym_p,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_text] = sym_text,
  [sym_integer] = sym_integer,
  [sym_identifier] = sym_identifier,
  [sym_format_string] = sym_format_string,
  [sym_maybe_format] = sym_maybe_format,
  [sym_format] = sym_format,
  [sym_fill] = sym_fill,
  [sym_align] = sym_align,
  [sym_sign] = sym_sign,
  [sym_type] = sym_type,
  [sym_count] = sym_count,
  [sym_parameter] = sym_parameter,
  [sym_argument] = sym_argument,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
  [alias_sym_width] = alias_sym_width,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_fill_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_o] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_p] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym_maybe_format] = {
    .visible = true,
    .named = true,
  },
  [sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_fill] = {
    .visible = true,
    .named = true,
  },
  [sym_align] = {
    .visible = true,
    .named = true,
  },
  [sym_sign] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_count] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_width] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_width,
  },
  [2] = {
    [3] = alias_sym_width,
  },
  [3] = {
    [4] = alias_sym_width,
  },
  [4] = {
    [5] = alias_sym_width,
  },
  [5] = {
    [6] = alias_sym_width,
  },
  [6] = {
    [7] = alias_sym_width,
  },
  [7] = {
    [8] = alias_sym_width,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_count, 2,
    sym_count,
    alias_sym_width,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '#', 12,
        '$', 37,
        '*', 15,
        '+', 25,
        '-', 26,
        '.', 14,
        '0', 13,
        ':', 11,
        '<', 22,
        '>', 24,
        '?', 27,
        'E', 36,
        'X', 32,
        '^', 23,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '{', 10,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 12,
        '$', 37,
        '+', 25,
        '-', 26,
        '.', 14,
        '0', 13,
        ':', 11,
        '?', 27,
        'E', 36,
        'X', 32,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 12,
        '+', 25,
        '-', 26,
        '.', 14,
        '0', 13,
        '<', 22,
        '>', 24,
        '?', 27,
        'E', 36,
        'X', 32,
        '^', 23,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '.', 14,
        '<', 22,
        '>', 24,
        '?', 27,
        'E', 36,
        'X', 32,
        '^', 23,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(9);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(8);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(9);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_fill_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_fill_token1);
      ADVANCE_MAP(
        '#', 12,
        '+', 25,
        '-', 26,
        '.', 14,
        '<', 22,
        '>', 24,
        '?', 27,
        'E', 36,
        'X', 32,
        '^', 23,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '0' || '9' < lookahead)) ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_fill_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_fill_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_x_QMARK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_X_QMARK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_o);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_x);
      if (lookahead == '?') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_X);
      if (lookahead == '?') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_p);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_b);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_e);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_E);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 38},
  [75] = {.lex_state = 38},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 38},
  [79] = {.lex_state = 38},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 38},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 38},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 38},
  [88] = {.lex_state = 38},
  [89] = {.lex_state = 38},
  [90] = {.lex_state = 38},
  [91] = {.lex_state = 38},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 38},
  [94] = {.lex_state = 38},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 38},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 38},
  [100] = {.lex_state = 38},
  [101] = {.lex_state = 38},
  [102] = {.lex_state = 38},
  [103] = {.lex_state = 38},
  [104] = {.lex_state = 38},
  [105] = {.lex_state = 38},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 38},
  [109] = {.lex_state = 38},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 38},
  [113] = {.lex_state = 38},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 38},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 38},
  [118] = {.lex_state = 38},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 38},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 38},
  [123] = {.lex_state = 38},
  [124] = {.lex_state = 1},
  [125] = {.lex_state = 38},
  [126] = {.lex_state = 38},
  [127] = {.lex_state = 1},
  [128] = {.lex_state = 38},
  [129] = {.lex_state = 38},
  [130] = {.lex_state = 38},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 1},
  [133] = {.lex_state = 1},
  [134] = {.lex_state = 38},
  [135] = {.lex_state = 38},
  [136] = {.lex_state = 38},
  [137] = {.lex_state = 38},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 38},
  [140] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_x_QMARK] = ACTIONS(1),
    [anon_sym_X_QMARK] = ACTIONS(1),
    [anon_sym_o] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_p] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_format_string] = STATE(83),
    [sym_text] = ACTIONS(3),
  },
  [2] = {
    [sym_fill] = STATE(68),
    [sym_align] = STATE(4),
    [sym_sign] = STATE(10),
    [sym_type] = STATE(110),
    [sym_count] = STATE(25),
    [sym_parameter] = STATE(36),
    [sym_argument] = STATE(84),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_0] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(11),
    [aux_sym_fill_token1] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_CARET] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_x_QMARK] = ACTIONS(19),
    [anon_sym_X_QMARK] = ACTIONS(19),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [3] = {
    [sym_fill] = STATE(69),
    [sym_align] = STATE(5),
    [sym_sign] = STATE(9),
    [sym_type] = STATE(116),
    [sym_count] = STATE(26),
    [sym_parameter] = STATE(36),
    [sym_argument] = STATE(84),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_0] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(31),
    [aux_sym_fill_token1] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_CARET] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_x_QMARK] = ACTIONS(19),
    [anon_sym_X_QMARK] = ACTIONS(19),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [4] = {
    [sym_sign] = STATE(9),
    [sym_type] = STATE(116),
    [sym_count] = STATE(26),
    [sym_parameter] = STATE(36),
    [sym_argument] = STATE(84),
    [anon_sym_POUND] = ACTIONS(33),
    [anon_sym_0] = ACTIONS(35),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_x_QMARK] = ACTIONS(43),
    [anon_sym_X_QMARK] = ACTIONS(43),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [5] = {
    [sym_sign] = STATE(11),
    [sym_type] = STATE(124),
    [sym_count] = STATE(27),
    [sym_parameter] = STATE(36),
    [sym_argument] = STATE(84),
    [anon_sym_POUND] = ACTIONS(45),
    [anon_sym_0] = ACTIONS(47),
    [anon_sym_DOT] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_x_QMARK] = ACTIONS(43),
    [anon_sym_X_QMARK] = ACTIONS(43),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [6] = {
    [sym_sign] = STATE(12),
    [sym_type] = STATE(111),
    [sym_count] = STATE(28),
    [sym_parameter] = STATE(36),
    [sym_argument] = STATE(84),
    [anon_sym_POUND] = ACTIONS(53),
    [anon_sym_0] = ACTIONS(55),
    [anon_sym_DOT] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_x_QMARK] = ACTIONS(43),
    [anon_sym_X_QMARK] = ACTIONS(43),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [7] = {
    [sym_type] = STATE(124),
    [sym_count] = STATE(27),
    [sym_parameter] = STATE(36),
    [sym_argument] = STATE(84),
    [anon_sym_DOT] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_CARET] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_x_QMARK] = ACTIONS(43),
    [anon_sym_X_QMARK] = ACTIONS(43),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(63),
    [sym_identifier] = ACTIONS(23),
  },
  [8] = {
    [sym_type] = STATE(116),
    [sym_count] = STATE(26),
    [sym_parameter] = STATE(36),
    [sym_argument] = STATE(84),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_CARET] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_x_QMARK] = ACTIONS(43),
    [anon_sym_X_QMARK] = ACTIONS(43),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(63),
    [sym_identifier] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_0,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(124), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [45] = 12,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_0,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(26), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(116), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [90] = 12,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_POUND,
    ACTIONS(55), 1,
      anon_sym_0,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(111), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [135] = 12,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_POUND,
    ACTIONS(67), 1,
      anon_sym_0,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(76), 1,
      sym_type,
    STATE(84), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [180] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_0,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(124), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [222] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(55), 1,
      anon_sym_0,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(111), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [264] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_0,
    ACTIONS(75), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(98), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [306] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_0,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(26), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(116), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [348] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_0,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(76), 1,
      sym_type,
    STATE(84), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [390] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 1,
      sym_integer,
    STATE(27), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(124), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [429] = 2,
    ACTIONS(79), 8,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(81), 10,
      anon_sym_0,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_integer,
      sym_identifier,
  [452] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 1,
      sym_integer,
    STATE(28), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(111), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [491] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(76), 1,
      sym_type,
    STATE(84), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [530] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(83), 1,
      anon_sym_DOT,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(106), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [569] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(75), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
    STATE(98), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [608] = 2,
    ACTIONS(87), 6,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(89), 10,
      anon_sym_0,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_integer,
      sym_identifier,
  [629] = 5,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [654] = 5,
    ACTIONS(95), 1,
      anon_sym_DOT,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [679] = 5,
    ACTIONS(99), 1,
      anon_sym_DOT,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [704] = 5,
    ACTIONS(103), 1,
      anon_sym_DOT,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [729] = 5,
    ACTIONS(107), 1,
      anon_sym_DOT,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(114), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [754] = 3,
    ACTIONS(115), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 5,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(113), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [775] = 5,
    ACTIONS(117), 1,
      anon_sym_DOT,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [800] = 5,
    ACTIONS(121), 1,
      anon_sym_DOT,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    STATE(127), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [825] = 4,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(132), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [847] = 4,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(138), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [869] = 4,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(111), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [891] = 2,
    ACTIONS(111), 5,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(113), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [909] = 4,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(133), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [931] = 4,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [953] = 4,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [975] = 4,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(124), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [997] = 4,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1019] = 4,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(106), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1041] = 4,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(140), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1063] = 2,
    ACTIONS(137), 5,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(139), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1081] = 4,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(119), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1103] = 4,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(121), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1125] = 4,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(131), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1147] = 4,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1169] = 6,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      aux_sym_format_string_repeat1,
    STATE(102), 1,
      sym_maybe_format,
    STATE(125), 1,
      sym_format,
    ACTIONS(149), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [1189] = 6,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      aux_sym_format_string_repeat1,
    STATE(102), 1,
      sym_maybe_format,
    STATE(125), 1,
      sym_format,
    ACTIONS(157), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [1209] = 6,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      aux_sym_format_string_repeat1,
    STATE(102), 1,
      sym_maybe_format,
    STATE(125), 1,
      sym_format,
    ACTIONS(157), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [1229] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(163), 1,
      anon_sym_STAR,
    ACTIONS(165), 1,
      sym_identifier,
    STATE(36), 1,
      sym_parameter,
    STATE(42), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1248] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(167), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(40), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1267] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(169), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(43), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1286] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(45), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1305] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(173), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(41), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1324] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(175), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(46), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1343] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(177), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(37), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1362] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(179), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(39), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1381] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(181), 1,
      anon_sym_STAR,
    STATE(33), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
  [1400] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(48), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1419] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(185), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(47), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1438] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(187), 1,
      anon_sym_STAR,
    STATE(34), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
  [1457] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_STAR,
    STATE(35), 1,
      sym_count,
    STATE(36), 1,
      sym_parameter,
    STATE(84), 1,
      sym_argument,
  [1476] = 6,
    ACTIONS(63), 1,
      sym_integer,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(191), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_parameter,
    STATE(38), 1,
      sym_count,
    STATE(84), 1,
      sym_argument,
  [1495] = 4,
    ACTIONS(193), 1,
      anon_sym_COLON,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_argument,
    ACTIONS(165), 2,
      sym_integer,
      sym_identifier,
  [1509] = 2,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(147), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [1518] = 2,
    STATE(5), 1,
      sym_align,
    ACTIONS(199), 3,
      anon_sym_LT,
      anon_sym_CARET,
      anon_sym_GT,
  [1527] = 2,
    STATE(6), 1,
      sym_align,
    ACTIONS(199), 3,
      anon_sym_LT,
      anon_sym_CARET,
      anon_sym_GT,
  [1536] = 1,
    ACTIONS(61), 3,
      anon_sym_LT,
      anon_sym_CARET,
      anon_sym_GT,
  [1542] = 1,
    ACTIONS(115), 3,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
  [1548] = 2,
    ACTIONS(201), 1,
      anon_sym_COLON,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
  [1555] = 2,
    ACTIONS(115), 1,
      anon_sym_DOLLAR,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
  [1562] = 1,
    ACTIONS(207), 1,
      sym_text,
  [1566] = 1,
    ACTIONS(209), 1,
      sym_text,
  [1570] = 1,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
  [1574] = 1,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
  [1578] = 1,
    ACTIONS(211), 1,
      sym_text,
  [1582] = 1,
    ACTIONS(213), 1,
      sym_text,
  [1586] = 1,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
  [1590] = 1,
    ACTIONS(217), 1,
      sym_text,
  [1594] = 1,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
  [1598] = 1,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
  [1602] = 1,
    ACTIONS(223), 1,
      anon_sym_DOLLAR,
  [1606] = 1,
    ACTIONS(225), 1,
      sym_text,
  [1610] = 1,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
  [1614] = 1,
    ACTIONS(229), 1,
      sym_text,
  [1618] = 1,
    ACTIONS(231), 1,
      sym_text,
  [1622] = 1,
    ACTIONS(233), 1,
      sym_text,
  [1626] = 1,
    ACTIONS(235), 1,
      sym_text,
  [1630] = 1,
    ACTIONS(237), 1,
      sym_text,
  [1634] = 1,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [1638] = 1,
    ACTIONS(241), 1,
      sym_text,
  [1642] = 1,
    ACTIONS(243), 1,
      sym_text,
  [1646] = 1,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
  [1650] = 1,
    ACTIONS(247), 1,
      sym_text,
  [1654] = 1,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
  [1658] = 1,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
  [1662] = 1,
    ACTIONS(251), 1,
      sym_text,
  [1666] = 1,
    ACTIONS(253), 1,
      sym_text,
  [1670] = 1,
    ACTIONS(255), 1,
      sym_text,
  [1674] = 1,
    ACTIONS(257), 1,
      sym_text,
  [1678] = 1,
    ACTIONS(259), 1,
      sym_text,
  [1682] = 1,
    ACTIONS(261), 1,
      sym_text,
  [1686] = 1,
    ACTIONS(263), 1,
      sym_text,
  [1690] = 1,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
  [1694] = 1,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
  [1698] = 1,
    ACTIONS(267), 1,
      sym_text,
  [1702] = 1,
    ACTIONS(269), 1,
      sym_text,
  [1706] = 1,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
  [1710] = 1,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
  [1714] = 1,
    ACTIONS(271), 1,
      sym_text,
  [1718] = 1,
    ACTIONS(273), 1,
      sym_text,
  [1722] = 1,
    ACTIONS(275), 1,
      anon_sym_RBRACE,
  [1726] = 1,
    ACTIONS(277), 1,
      sym_text,
  [1730] = 1,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
  [1734] = 1,
    ACTIONS(279), 1,
      sym_text,
  [1738] = 1,
    ACTIONS(281), 1,
      sym_text,
  [1742] = 1,
    ACTIONS(283), 1,
      anon_sym_RBRACE,
  [1746] = 1,
    ACTIONS(285), 1,
      sym_text,
  [1750] = 1,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
  [1754] = 1,
    ACTIONS(287), 1,
      sym_text,
  [1758] = 1,
    ACTIONS(289), 1,
      sym_text,
  [1762] = 1,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
  [1766] = 1,
    ACTIONS(291), 1,
      sym_text,
  [1770] = 1,
    ACTIONS(293), 1,
      sym_text,
  [1774] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
  [1778] = 1,
    ACTIONS(297), 1,
      sym_text,
  [1782] = 1,
    ACTIONS(299), 1,
      sym_text,
  [1786] = 1,
    ACTIONS(301), 1,
      sym_text,
  [1790] = 1,
    ACTIONS(303), 1,
      anon_sym_RBRACE,
  [1794] = 1,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
  [1798] = 1,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
  [1802] = 1,
    ACTIONS(309), 1,
      sym_text,
  [1806] = 1,
    ACTIONS(311), 1,
      sym_text,
  [1810] = 1,
    ACTIONS(313), 1,
      sym_text,
  [1814] = 1,
    ACTIONS(315), 1,
      sym_text,
  [1818] = 1,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
  [1822] = 1,
    ACTIONS(319), 1,
      sym_text,
  [1826] = 1,
    ACTIONS(321), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 45,
  [SMALL_STATE(11)] = 90,
  [SMALL_STATE(12)] = 135,
  [SMALL_STATE(13)] = 180,
  [SMALL_STATE(14)] = 222,
  [SMALL_STATE(15)] = 264,
  [SMALL_STATE(16)] = 306,
  [SMALL_STATE(17)] = 348,
  [SMALL_STATE(18)] = 390,
  [SMALL_STATE(19)] = 429,
  [SMALL_STATE(20)] = 452,
  [SMALL_STATE(21)] = 491,
  [SMALL_STATE(22)] = 530,
  [SMALL_STATE(23)] = 569,
  [SMALL_STATE(24)] = 608,
  [SMALL_STATE(25)] = 629,
  [SMALL_STATE(26)] = 654,
  [SMALL_STATE(27)] = 679,
  [SMALL_STATE(28)] = 704,
  [SMALL_STATE(29)] = 729,
  [SMALL_STATE(30)] = 754,
  [SMALL_STATE(31)] = 775,
  [SMALL_STATE(32)] = 800,
  [SMALL_STATE(33)] = 825,
  [SMALL_STATE(34)] = 847,
  [SMALL_STATE(35)] = 869,
  [SMALL_STATE(36)] = 891,
  [SMALL_STATE(37)] = 909,
  [SMALL_STATE(38)] = 931,
  [SMALL_STATE(39)] = 953,
  [SMALL_STATE(40)] = 975,
  [SMALL_STATE(41)] = 997,
  [SMALL_STATE(42)] = 1019,
  [SMALL_STATE(43)] = 1041,
  [SMALL_STATE(44)] = 1063,
  [SMALL_STATE(45)] = 1081,
  [SMALL_STATE(46)] = 1103,
  [SMALL_STATE(47)] = 1125,
  [SMALL_STATE(48)] = 1147,
  [SMALL_STATE(49)] = 1169,
  [SMALL_STATE(50)] = 1189,
  [SMALL_STATE(51)] = 1209,
  [SMALL_STATE(52)] = 1229,
  [SMALL_STATE(53)] = 1248,
  [SMALL_STATE(54)] = 1267,
  [SMALL_STATE(55)] = 1286,
  [SMALL_STATE(56)] = 1305,
  [SMALL_STATE(57)] = 1324,
  [SMALL_STATE(58)] = 1343,
  [SMALL_STATE(59)] = 1362,
  [SMALL_STATE(60)] = 1381,
  [SMALL_STATE(61)] = 1400,
  [SMALL_STATE(62)] = 1419,
  [SMALL_STATE(63)] = 1438,
  [SMALL_STATE(64)] = 1457,
  [SMALL_STATE(65)] = 1476,
  [SMALL_STATE(66)] = 1495,
  [SMALL_STATE(67)] = 1509,
  [SMALL_STATE(68)] = 1518,
  [SMALL_STATE(69)] = 1527,
  [SMALL_STATE(70)] = 1536,
  [SMALL_STATE(71)] = 1542,
  [SMALL_STATE(72)] = 1548,
  [SMALL_STATE(73)] = 1555,
  [SMALL_STATE(74)] = 1562,
  [SMALL_STATE(75)] = 1566,
  [SMALL_STATE(76)] = 1570,
  [SMALL_STATE(77)] = 1574,
  [SMALL_STATE(78)] = 1578,
  [SMALL_STATE(79)] = 1582,
  [SMALL_STATE(80)] = 1586,
  [SMALL_STATE(81)] = 1590,
  [SMALL_STATE(82)] = 1594,
  [SMALL_STATE(83)] = 1598,
  [SMALL_STATE(84)] = 1602,
  [SMALL_STATE(85)] = 1606,
  [SMALL_STATE(86)] = 1610,
  [SMALL_STATE(87)] = 1614,
  [SMALL_STATE(88)] = 1618,
  [SMALL_STATE(89)] = 1622,
  [SMALL_STATE(90)] = 1626,
  [SMALL_STATE(91)] = 1630,
  [SMALL_STATE(92)] = 1634,
  [SMALL_STATE(93)] = 1638,
  [SMALL_STATE(94)] = 1642,
  [SMALL_STATE(95)] = 1646,
  [SMALL_STATE(96)] = 1650,
  [SMALL_STATE(97)] = 1654,
  [SMALL_STATE(98)] = 1658,
  [SMALL_STATE(99)] = 1662,
  [SMALL_STATE(100)] = 1666,
  [SMALL_STATE(101)] = 1670,
  [SMALL_STATE(102)] = 1674,
  [SMALL_STATE(103)] = 1678,
  [SMALL_STATE(104)] = 1682,
  [SMALL_STATE(105)] = 1686,
  [SMALL_STATE(106)] = 1690,
  [SMALL_STATE(107)] = 1694,
  [SMALL_STATE(108)] = 1698,
  [SMALL_STATE(109)] = 1702,
  [SMALL_STATE(110)] = 1706,
  [SMALL_STATE(111)] = 1710,
  [SMALL_STATE(112)] = 1714,
  [SMALL_STATE(113)] = 1718,
  [SMALL_STATE(114)] = 1722,
  [SMALL_STATE(115)] = 1726,
  [SMALL_STATE(116)] = 1730,
  [SMALL_STATE(117)] = 1734,
  [SMALL_STATE(118)] = 1738,
  [SMALL_STATE(119)] = 1742,
  [SMALL_STATE(120)] = 1746,
  [SMALL_STATE(121)] = 1750,
  [SMALL_STATE(122)] = 1754,
  [SMALL_STATE(123)] = 1758,
  [SMALL_STATE(124)] = 1762,
  [SMALL_STATE(125)] = 1766,
  [SMALL_STATE(126)] = 1770,
  [SMALL_STATE(127)] = 1774,
  [SMALL_STATE(128)] = 1778,
  [SMALL_STATE(129)] = 1782,
  [SMALL_STATE(130)] = 1786,
  [SMALL_STATE(131)] = 1790,
  [SMALL_STATE(132)] = 1794,
  [SMALL_STATE(133)] = 1798,
  [SMALL_STATE(134)] = 1802,
  [SMALL_STATE(135)] = 1806,
  [SMALL_STATE(136)] = 1810,
  [SMALL_STATE(137)] = 1814,
  [SMALL_STATE(138)] = 1818,
  [SMALL_STATE(139)] = 1822,
  [SMALL_STATE(140)] = 1826,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fill, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_align, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sign, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sign, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_count, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 10, 0, 7),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 7, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 7, 0, 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 7, 0, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [221] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 7, 0, 4),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 7, 0, 1),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 8, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 8, 0, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 8, 0, 2),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 1),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 8, 0, 5),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 8, 0, 4),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 6, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 6, 0, 3),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 9, 0, 3),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 9, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 9, 0, 5),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 9, 0, 4),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 9, 0, 6),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 6, 0, 2),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 10, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 10, 0, 5),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 10, 0, 4),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 10, 0, 6),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_maybe_format, 1, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 6, 0, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 11, 0, 5),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 11, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 11, 0, 6),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 11, 0, 7),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 12, 0, 6),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 12, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 12, 0, 7),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 13, 0, 7),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rustfmt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
