#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  anon_sym_LBRACE = 3,
  anon_sym_COLON = 4,
  anon_sym_POUND = 5,
  anon_sym_0 = 6,
  anon_sym_DOT = 7,
  anon_sym_STAR = 8,
  anon_sym_RBRACE = 9,
  sym_fill = 10,
  anon_sym_LT = 11,
  anon_sym_CARET = 12,
  anon_sym_GT = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_QMARK = 16,
  anon_sym_x_QMARK = 17,
  anon_sym_X_QMARK = 18,
  anon_sym_o = 19,
  anon_sym_x = 20,
  anon_sym_X = 21,
  anon_sym_p = 22,
  anon_sym_b = 23,
  anon_sym_e = 24,
  anon_sym_E = 25,
  anon_sym_DOLLAR = 26,
  sym_text = 27,
  sym_integer = 28,
  sym_identifier = 29,
  sym_format_string = 30,
  sym_maybe_format = 31,
  sym_format = 32,
  sym_align = 33,
  sym_sign = 34,
  sym_type = 35,
  sym_count = 36,
  sym_parameter = 37,
  sym_argument = 38,
  aux_sym_format_string_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_POUND] = "#",
  [anon_sym_0] = "0",
  [anon_sym_DOT] = ".",
  [anon_sym_STAR] = "*",
  [anon_sym_RBRACE] = "}",
  [sym_fill] = "fill",
  [anon_sym_LT] = "<",
  [anon_sym_CARET] = "^",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_QMARK] = "\?",
  [anon_sym_x_QMARK] = "x\?",
  [anon_sym_X_QMARK] = "X\?",
  [anon_sym_o] = "o",
  [anon_sym_x] = "x",
  [anon_sym_X] = "X",
  [anon_sym_p] = "p",
  [anon_sym_b] = "b",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym_DOLLAR] = "$",
  [sym_text] = "text",
  [sym_integer] = "integer",
  [sym_identifier] = "identifier",
  [sym_format_string] = "format_string",
  [sym_maybe_format] = "maybe_format",
  [sym_format] = "format",
  [sym_align] = "align",
  [sym_sign] = "sign",
  [sym_type] = "type",
  [sym_count] = "count",
  [sym_parameter] = "parameter",
  [sym_argument] = "argument",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_fill] = sym_fill,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_x_QMARK] = anon_sym_x_QMARK,
  [anon_sym_X_QMARK] = anon_sym_X_QMARK,
  [anon_sym_o] = anon_sym_o,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_p] = anon_sym_p,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_text] = sym_text,
  [sym_integer] = sym_integer,
  [sym_identifier] = sym_identifier,
  [sym_format_string] = sym_format_string,
  [sym_maybe_format] = sym_maybe_format,
  [sym_format] = sym_format,
  [sym_align] = sym_align,
  [sym_sign] = sym_sign,
  [sym_type] = sym_type,
  [sym_count] = sym_count,
  [sym_parameter] = sym_parameter,
  [sym_argument] = sym_argument,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_fill] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_o] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_p] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym_maybe_format] = {
    .visible = true,
    .named = true,
  },
  [sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_align] = {
    .visible = true,
    .named = true,
  },
  [sym_sign] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_count] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '#', 12,
        '$', 37,
        '*', 15,
        '+', 25,
        '-', 26,
        '.', 14,
        '0', 13,
        ':', 11,
        '<', 22,
        '>', 24,
        '?', 27,
        'E', 36,
        'X', 32,
        '^', 23,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '{', 10,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '+') ADVANCE(25);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '0') ADVANCE(13);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == '?') ADVANCE(27);
      if (lookahead == 'E') ADVANCE(36);
      if (lookahead == 'X') ADVANCE(32);
      if (lookahead == '^') ADVANCE(23);
      if (lookahead == 'b') ADVANCE(34);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == 'o') ADVANCE(30);
      if (lookahead == 'p') ADVANCE(33);
      if (lookahead == 'x') ADVANCE(31);
      if (lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 12,
        '$', 37,
        '+', 25,
        '-', 26,
        '.', 14,
        '0', 13,
        ':', 11,
        '?', 27,
        'E', 36,
        'X', 32,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '.', 14,
        '?', 27,
        'E', 36,
        'X', 32,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(9);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(8);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(9);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_fill);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_fill);
      ADVANCE_MAP(
        '#', 12,
        '+', 25,
        '-', 26,
        '.', 14,
        '0', 13,
        '<', 22,
        '>', 24,
        '?', 27,
        'E', 36,
        'X', 32,
        '^', 23,
        'b', 34,
        'e', 35,
        'o', 30,
        'p', 33,
        'x', 31,
        '}', 16,
      );
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_fill);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_fill);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_x_QMARK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_X_QMARK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_o);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_x);
      if (lookahead == '?') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_X);
      if (lookahead == '?') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_p);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_b);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_e);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_E);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 38},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 38},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 38},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 38},
  [69] = {.lex_state = 38},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 38},
  [72] = {.lex_state = 38},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 38},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 38},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 38},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 38},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 38},
  [84] = {.lex_state = 38},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 38},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_x_QMARK] = ACTIONS(1),
    [anon_sym_X_QMARK] = ACTIONS(1),
    [anon_sym_o] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_p] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_format_string] = STATE(74),
    [sym_text] = ACTIONS(3),
  },
  [2] = {
    [sym_align] = STATE(4),
    [sym_sign] = STATE(7),
    [sym_type] = STATE(76),
    [sym_count] = STATE(24),
    [sym_parameter] = STATE(40),
    [sym_argument] = STATE(65),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_0] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(11),
    [sym_fill] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_CARET] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_x_QMARK] = ACTIONS(19),
    [anon_sym_X_QMARK] = ACTIONS(19),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [3] = {
    [sym_align] = STATE(5),
    [sym_sign] = STATE(8),
    [sym_type] = STATE(61),
    [sym_count] = STATE(26),
    [sym_parameter] = STATE(40),
    [sym_argument] = STATE(65),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_0] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(31),
    [sym_fill] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_CARET] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_x_QMARK] = ACTIONS(19),
    [anon_sym_X_QMARK] = ACTIONS(19),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [4] = {
    [sym_sign] = STATE(8),
    [sym_type] = STATE(61),
    [sym_count] = STATE(26),
    [sym_parameter] = STATE(40),
    [sym_argument] = STATE(65),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_0] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_x_QMARK] = ACTIONS(43),
    [anon_sym_X_QMARK] = ACTIONS(43),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [5] = {
    [sym_sign] = STATE(10),
    [sym_type] = STATE(64),
    [sym_count] = STATE(28),
    [sym_parameter] = STATE(40),
    [sym_argument] = STATE(65),
    [anon_sym_POUND] = ACTIONS(45),
    [anon_sym_0] = ACTIONS(47),
    [anon_sym_DOT] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_x_QMARK] = ACTIONS(43),
    [anon_sym_X_QMARK] = ACTIONS(43),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [6] = {
    [sym_sign] = STATE(9),
    [sym_type] = STATE(70),
    [sym_count] = STATE(27),
    [sym_parameter] = STATE(40),
    [sym_argument] = STATE(65),
    [anon_sym_POUND] = ACTIONS(53),
    [anon_sym_0] = ACTIONS(55),
    [anon_sym_DOT] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_x_QMARK] = ACTIONS(43),
    [anon_sym_X_QMARK] = ACTIONS(43),
    [anon_sym_o] = ACTIONS(19),
    [anon_sym_x] = ACTIONS(19),
    [anon_sym_X] = ACTIONS(19),
    [anon_sym_p] = ACTIONS(19),
    [anon_sym_b] = ACTIONS(19),
    [anon_sym_e] = ACTIONS(19),
    [anon_sym_E] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_0,
    ACTIONS(35), 1,
      anon_sym_POUND,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(26), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(61), 1,
      sym_type,
    STATE(65), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [45] = 12,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_0,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(64), 1,
      sym_type,
    STATE(65), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [90] = 12,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(61), 1,
      anon_sym_POUND,
    ACTIONS(63), 1,
      anon_sym_0,
    ACTIONS(65), 1,
      anon_sym_DOT,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(80), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [135] = 12,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_POUND,
    ACTIONS(55), 1,
      anon_sym_0,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(70), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [180] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_0,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(26), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(61), 1,
      sym_type,
    STATE(65), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [222] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_0,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(64), 1,
      sym_type,
    STATE(65), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [264] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_0,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(67), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [306] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_0,
    ACTIONS(65), 1,
      anon_sym_DOT,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(80), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [348] = 11,
    ACTIONS(21), 1,
      sym_integer,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(55), 1,
      anon_sym_0,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(70), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [390] = 2,
    ACTIONS(75), 8,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(77), 10,
      anon_sym_0,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_integer,
      sym_identifier,
  [413] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_integer,
    STATE(28), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(64), 1,
      sym_type,
    STATE(65), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [452] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_integer,
    STATE(26), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(61), 1,
      sym_type,
    STATE(65), 1,
      sym_argument,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [491] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_DOT,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_integer,
    STATE(29), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(80), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [530] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_integer,
    STATE(27), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(70), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [569] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_integer,
    STATE(30), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(67), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [608] = 10,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(81), 1,
      anon_sym_DOT,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
    STATE(73), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 7,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
  [647] = 2,
    ACTIONS(85), 6,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(87), 10,
      anon_sym_0,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_integer,
      sym_identifier,
  [668] = 5,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [693] = 3,
    ACTIONS(93), 1,
      anon_sym_DOLLAR,
    ACTIONS(89), 5,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(91), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [714] = 5,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [739] = 5,
    ACTIONS(65), 1,
      anon_sym_DOT,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [764] = 5,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [789] = 5,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [814] = 5,
    ACTIONS(81), 1,
      anon_sym_DOT,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [839] = 5,
    ACTIONS(95), 1,
      anon_sym_DOT,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [864] = 2,
    ACTIONS(99), 5,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(101), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [882] = 4,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(85), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [904] = 4,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [926] = 4,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [948] = 4,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [970] = 4,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [992] = 4,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1014] = 4,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1036] = 2,
    ACTIONS(89), 5,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(91), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1054] = 4,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      sym_type,
    ACTIONS(43), 3,
      anon_sym_QMARK,
      anon_sym_x_QMARK,
      anon_sym_X_QMARK,
    ACTIONS(19), 8,
      anon_sym_o,
      anon_sym_x,
      anon_sym_X,
      anon_sym_p,
      anon_sym_b,
      anon_sym_e,
      anon_sym_E,
      sym_identifier,
  [1076] = 6,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      aux_sym_format_string_repeat1,
    STATE(71), 1,
      sym_format,
    STATE(83), 1,
      sym_maybe_format,
    ACTIONS(109), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [1096] = 6,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      aux_sym_format_string_repeat1,
    STATE(71), 1,
      sym_format,
    STATE(83), 1,
      sym_maybe_format,
    ACTIONS(115), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [1116] = 6,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    STATE(42), 1,
      aux_sym_format_string_repeat1,
    STATE(71), 1,
      sym_format,
    STATE(83), 1,
      sym_maybe_format,
    ACTIONS(109), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [1136] = 6,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(35), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
  [1155] = 6,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(127), 1,
      anon_sym_STAR,
    STATE(34), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
  [1174] = 6,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(129), 1,
      anon_sym_STAR,
    STATE(38), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
  [1193] = 6,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(131), 1,
      anon_sym_STAR,
    STATE(37), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
  [1212] = 6,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(133), 1,
      anon_sym_STAR,
    STATE(40), 1,
      sym_parameter,
    STATE(41), 1,
      sym_count,
    STATE(65), 1,
      sym_argument,
  [1231] = 6,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(135), 1,
      anon_sym_STAR,
    STATE(39), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
  [1250] = 6,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
  [1269] = 6,
    ACTIONS(79), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(139), 1,
      anon_sym_STAR,
    STATE(33), 1,
      sym_count,
    STATE(40), 1,
      sym_parameter,
    STATE(65), 1,
      sym_argument,
  [1288] = 4,
    ACTIONS(141), 1,
      anon_sym_COLON,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      sym_argument,
    ACTIONS(125), 2,
      sym_integer,
      sym_identifier,
  [1302] = 2,
    STATE(5), 1,
      sym_align,
    ACTIONS(145), 3,
      anon_sym_LT,
      anon_sym_CARET,
      anon_sym_GT,
  [1311] = 2,
    STATE(6), 1,
      sym_align,
    ACTIONS(145), 3,
      anon_sym_LT,
      anon_sym_CARET,
      anon_sym_GT,
  [1320] = 2,
    ACTIONS(147), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [1329] = 1,
    ACTIONS(93), 3,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
  [1335] = 2,
    ACTIONS(93), 1,
      anon_sym_DOLLAR,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
  [1342] = 2,
    ACTIONS(151), 1,
      anon_sym_COLON,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
  [1349] = 1,
    ACTIONS(155), 1,
      sym_text,
  [1353] = 1,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
  [1357] = 1,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
  [1361] = 1,
    ACTIONS(157), 1,
      sym_text,
  [1365] = 1,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
  [1369] = 1,
    ACTIONS(159), 1,
      anon_sym_DOLLAR,
  [1373] = 1,
    ACTIONS(161), 1,
      sym_text,
  [1377] = 1,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
  [1381] = 1,
    ACTIONS(163), 1,
      sym_text,
  [1385] = 1,
    ACTIONS(165), 1,
      sym_text,
  [1389] = 1,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
  [1393] = 1,
    ACTIONS(167), 1,
      sym_text,
  [1397] = 1,
    ACTIONS(169), 1,
      sym_text,
  [1401] = 1,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
  [1405] = 1,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
  [1409] = 1,
    ACTIONS(173), 1,
      sym_text,
  [1413] = 1,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
  [1417] = 1,
    ACTIONS(175), 1,
      sym_text,
  [1421] = 1,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
  [1425] = 1,
    ACTIONS(177), 1,
      sym_text,
  [1429] = 1,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
  [1433] = 1,
    ACTIONS(179), 1,
      sym_text,
  [1437] = 1,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
  [1441] = 1,
    ACTIONS(181), 1,
      sym_text,
  [1445] = 1,
    ACTIONS(183), 1,
      sym_text,
  [1449] = 1,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
  [1453] = 1,
    ACTIONS(187), 1,
      sym_text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 45,
  [SMALL_STATE(9)] = 90,
  [SMALL_STATE(10)] = 135,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 222,
  [SMALL_STATE(13)] = 264,
  [SMALL_STATE(14)] = 306,
  [SMALL_STATE(15)] = 348,
  [SMALL_STATE(16)] = 390,
  [SMALL_STATE(17)] = 413,
  [SMALL_STATE(18)] = 452,
  [SMALL_STATE(19)] = 491,
  [SMALL_STATE(20)] = 530,
  [SMALL_STATE(21)] = 569,
  [SMALL_STATE(22)] = 608,
  [SMALL_STATE(23)] = 647,
  [SMALL_STATE(24)] = 668,
  [SMALL_STATE(25)] = 693,
  [SMALL_STATE(26)] = 714,
  [SMALL_STATE(27)] = 739,
  [SMALL_STATE(28)] = 764,
  [SMALL_STATE(29)] = 789,
  [SMALL_STATE(30)] = 814,
  [SMALL_STATE(31)] = 839,
  [SMALL_STATE(32)] = 864,
  [SMALL_STATE(33)] = 882,
  [SMALL_STATE(34)] = 904,
  [SMALL_STATE(35)] = 926,
  [SMALL_STATE(36)] = 948,
  [SMALL_STATE(37)] = 970,
  [SMALL_STATE(38)] = 992,
  [SMALL_STATE(39)] = 1014,
  [SMALL_STATE(40)] = 1036,
  [SMALL_STATE(41)] = 1054,
  [SMALL_STATE(42)] = 1076,
  [SMALL_STATE(43)] = 1096,
  [SMALL_STATE(44)] = 1116,
  [SMALL_STATE(45)] = 1136,
  [SMALL_STATE(46)] = 1155,
  [SMALL_STATE(47)] = 1174,
  [SMALL_STATE(48)] = 1193,
  [SMALL_STATE(49)] = 1212,
  [SMALL_STATE(50)] = 1231,
  [SMALL_STATE(51)] = 1250,
  [SMALL_STATE(52)] = 1269,
  [SMALL_STATE(53)] = 1288,
  [SMALL_STATE(54)] = 1302,
  [SMALL_STATE(55)] = 1311,
  [SMALL_STATE(56)] = 1320,
  [SMALL_STATE(57)] = 1329,
  [SMALL_STATE(58)] = 1335,
  [SMALL_STATE(59)] = 1342,
  [SMALL_STATE(60)] = 1349,
  [SMALL_STATE(61)] = 1353,
  [SMALL_STATE(62)] = 1357,
  [SMALL_STATE(63)] = 1361,
  [SMALL_STATE(64)] = 1365,
  [SMALL_STATE(65)] = 1369,
  [SMALL_STATE(66)] = 1373,
  [SMALL_STATE(67)] = 1377,
  [SMALL_STATE(68)] = 1381,
  [SMALL_STATE(69)] = 1385,
  [SMALL_STATE(70)] = 1389,
  [SMALL_STATE(71)] = 1393,
  [SMALL_STATE(72)] = 1397,
  [SMALL_STATE(73)] = 1401,
  [SMALL_STATE(74)] = 1405,
  [SMALL_STATE(75)] = 1409,
  [SMALL_STATE(76)] = 1413,
  [SMALL_STATE(77)] = 1417,
  [SMALL_STATE(78)] = 1421,
  [SMALL_STATE(79)] = 1425,
  [SMALL_STATE(80)] = 1429,
  [SMALL_STATE(81)] = 1433,
  [SMALL_STATE(82)] = 1437,
  [SMALL_STATE(83)] = 1441,
  [SMALL_STATE(84)] = 1445,
  [SMALL_STATE(85)] = 1449,
  [SMALL_STATE(86)] = 1453,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_align, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sign, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sign, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_count, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_count, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 8, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 6, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_maybe_format, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 9, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 10, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 7, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 11, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 12, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 13, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rustfmt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
